### ISSUE TITLE
Roadmap Shroom 2019

### ISSUE THREAD

**Issue by ivanminutillo** [ivanminutillo/shroom#5]
## Jan - April 2019
- [ ] [Istallazione del server napoletano](https://github.com/ivanminutillo/shroom/milestone/3)
- [ ] [Demo Shroom / planning @ Macao](https://github.com/ivanminutillo/shroom/milestone/4)
- [ ] [Dataviz misurazione del valore @ Asilo](https://github.com/ivanminutillo/shroom/milestone/5)

## May - Aug 2019
- [ ] [Demo Shroom / inventory @ Asilo](https://github.com/ivanminutillo/shroom/milestone/6)
- [ ] [Demo Shroom / wallet @ Macao](https://github.com/ivanminutillo/shroom/milestone/7)
- [ ] [Dataviz misurazione del valore @ Macao & SoS](https://github.com/ivanminutillo/shroom/milestone/9)

## Sep - Dec 2019
- [ ] [Porting to p2p backend](https://github.com/ivanminutillo/shroom/milestone/10)
- [ ] [Mobile app](https://github.com/ivanminutillo/shroom/milestone/11)
- [ ] [Demo Shroom / wallet @ Scuola open source](https://github.com/ivanminutillo/shroom/milestone/8)
